-- MySQL Script generated by MySQL Workbench
-- Fri Jun 23 13:22:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RPG
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `RPG` ;

-- -----------------------------------------------------
-- Schema RPG
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RPG` DEFAULT CHARACTER SET utf8 ;
USE `RPG` ;

-- -----------------------------------------------------
-- Table `RPG`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RPG`.`usuario` ;

CREATE TABLE IF NOT EXISTS `RPG`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(256) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `data_nascimento` DATE NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RPG`.`raca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RPG`.`raca` ;

CREATE TABLE IF NOT EXISTS `RPG`.`raca` (
  `id_raca` INT NOT NULL AUTO_INCREMENT,
  `nome_raca` VARCHAR(45) NULL,
  PRIMARY KEY (`id_raca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RPG`.`personagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RPG`.`personagem` ;

CREATE TABLE IF NOT EXISTS `RPG`.`personagem` (
  `id_personagem` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_raca` INT NOT NULL,
  `nivel` INT NULL,
  `xp` DOUBLE NULL,
  `vida` INT NULL,
  `alinhamento` VARCHAR(45) NULL,
  `antecedente` VARCHAR(45) NULL,
  `faccao` VARCHAR(45) NULL,
  `inspiracao` INT NULL,
  `ca` INT NULL,
  `iniciativa` INT NULL,
  `deslocamento` INT NULL,
  `vida_atual` FLOAT NULL,
  `vida_temporaria` FLOAT NULL,
  PRIMARY KEY (`id_personagem`),
  CONSTRAINT `fk_personagem_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `RPG`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personagem_raca1`
    FOREIGN KEY (`id_raca`)
    REFERENCES `RPG`.`raca` (`id_raca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_personagem_usuario_idx` ON `RPG`.`personagem` (`id_usuario` ASC) VISIBLE;

CREATE INDEX `fk_personagem_raca1_idx` ON `RPG`.`personagem` (`id_raca` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `RPG`.`classe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RPG`.`classe` ;

CREATE TABLE IF NOT EXISTS `RPG`.`classe` (
  `id_classe` INT NOT NULL AUTO_INCREMENT,
  `nome_classe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_classe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RPG`.`classe_personagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RPG`.`classe_personagem` ;

CREATE TABLE IF NOT EXISTS `RPG`.`classe_personagem` (
  `id_classe_personagem` INT NOT NULL,
  `id_personagem` INT NOT NULL,
  `id_classe` INT NOT NULL,
  PRIMARY KEY (`id_classe_personagem`),
  CONSTRAINT `fk_classes_personagem_personagem1`
    FOREIGN KEY (`id_personagem`)
    REFERENCES `RPG`.`personagem` (`id_personagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classes_personagem_classe1`
    FOREIGN KEY (`id_classe`)
    REFERENCES `RPG`.`classe` (`id_classe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_classes_personagem_personagem1_idx` ON `RPG`.`classe_personagem` (`id_personagem` ASC) VISIBLE;

CREATE INDEX `fk_classes_personagem_classe1_idx` ON `RPG`.`classe_personagem` (`id_classe` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `RPG`.`atributos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RPG`.`atributos` ;

CREATE TABLE IF NOT EXISTS `RPG`.`atributos` (
  `id_atributos` INT NOT NULL AUTO_INCREMENT,
  `id_personagem` INT NOT NULL,
  `forca` INT NULL,
  `destreza` INT NULL,
  `constituicao` INT NULL,
  `inteligencia` INT NULL,
  `sabedoria` INT NULL,
  `carisma` INT NULL,
  `bonus_proficiencia` INT NULL,
  PRIMARY KEY (`id_atributos`),
  CONSTRAINT `fk_atributos_personagem1`
    FOREIGN KEY (`id_personagem`)
    REFERENCES `RPG`.`personagem` (`id_personagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_atributos_personagem1_idx` ON `RPG`.`atributos` (`id_personagem` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `RPG`.`pericia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RPG`.`pericia` ;

CREATE TABLE IF NOT EXISTS `RPG`.`pericia` (
  `id_pericia` INT NOT NULL AUTO_INCREMENT,
  `nome_pericia` VARCHAR(45) NOT NULL,
  `status_uso` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pericia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RPG`.`perificia_personagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RPG`.`perificia_personagem` ;

CREATE TABLE IF NOT EXISTS `RPG`.`perificia_personagem` (
  `id_perificia_personagem` INT NOT NULL AUTO_INCREMENT,
  `id_pericia` INT NOT NULL,
  `id_personagem` INT NOT NULL,
  PRIMARY KEY (`id_perificia_personagem`),
  CONSTRAINT `fk_perificia_personagem_pericia1`
    FOREIGN KEY (`id_pericia`)
    REFERENCES `RPG`.`pericia` (`id_pericia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perificia_personagem_personagem1`
    FOREIGN KEY (`id_personagem`)
    REFERENCES `RPG`.`personagem` (`id_personagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_perificia_personagem_pericia1_idx` ON `RPG`.`perificia_personagem` (`id_pericia` ASC) VISIBLE;

CREATE INDEX `fk_perificia_personagem_personagem1_idx` ON `RPG`.`perificia_personagem` (`id_personagem` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `RPG`.`tipo_dano`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RPG`.`tipo_dano` ;

CREATE TABLE IF NOT EXISTS `RPG`.`tipo_dano` (
  `id_tipo_dano` INT NOT NULL,
  `nome_tipo` VARCHAR(60) NULL,
  PRIMARY KEY (`id_tipo_dano`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RPG`.`magia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RPG`.`magia` ;

CREATE TABLE IF NOT EXISTS `RPG`.`magia` (
  `id_magia` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_dano` INT NOT NULL,
  `nome_magia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_magia`),
  CONSTRAINT `fk_magia_tipo_dano1`
    FOREIGN KEY (`id_tipo_dano`)
    REFERENCES `RPG`.`tipo_dano` (`id_tipo_dano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_magia_tipo_dano1_idx` ON `RPG`.`magia` (`id_tipo_dano` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `RPG`.`magia_personagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RPG`.`magia_personagem` ;

CREATE TABLE IF NOT EXISTS `RPG`.`magia_personagem` (
  `id_magia_personagem` INT NOT NULL AUTO_INCREMENT,
  `id_personagem` INT NOT NULL,
  `id_magia` INT NOT NULL,
  PRIMARY KEY (`id_magia_personagem`),
  CONSTRAINT `fk_magia_personagem_personagem1`
    FOREIGN KEY (`id_personagem`)
    REFERENCES `RPG`.`personagem` (`id_personagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_magia_personagem_magia1`
    FOREIGN KEY (`id_magia`)
    REFERENCES `RPG`.`magia` (`id_magia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_magia_personagem_personagem1_idx` ON `RPG`.`magia_personagem` (`id_personagem` ASC) VISIBLE;

CREATE INDEX `fk_magia_personagem_magia1_idx` ON `RPG`.`magia_personagem` (`id_magia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `RPG`.`espaco_magia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RPG`.`espaco_magia` ;

CREATE TABLE IF NOT EXISTS `RPG`.`espaco_magia` (
  `id_espaco_magia` INT NOT NULL AUTO_INCREMENT,
  `id_personagem` INT NOT NULL,
  `nivel_magia` INT NOT NULL,
  `qtd_utilizado` INT NULL,
  PRIMARY KEY (`id_espaco_magia`),
  CONSTRAINT `fk_espaco_magia_personagem1`
    FOREIGN KEY (`id_personagem`)
    REFERENCES `RPG`.`personagem` (`id_personagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_espaco_magia_personagem1_idx` ON `RPG`.`espaco_magia` (`id_personagem` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `RPG`.`truque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RPG`.`truque` ;

CREATE TABLE IF NOT EXISTS `RPG`.`truque` (
  `id_truque` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_dano` INT NOT NULL,
  `nome_truque` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_truque`),
  CONSTRAINT `fk_truque_tipo_dano1`
    FOREIGN KEY (`id_tipo_dano`)
    REFERENCES `RPG`.`tipo_dano` (`id_tipo_dano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_truque_tipo_dano1_idx` ON `RPG`.`truque` (`id_tipo_dano` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `RPG`.`truque_personagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RPG`.`truque_personagem` ;

CREATE TABLE IF NOT EXISTS `RPG`.`truque_personagem` (
  `id_truque_personagem` INT NOT NULL AUTO_INCREMENT,
  `truque_id_truque` INT NOT NULL,
  `personagem_id_personagem` INT NOT NULL,
  PRIMARY KEY (`id_truque_personagem`),
  CONSTRAINT `fk_truque_personagem_truque1`
    FOREIGN KEY (`truque_id_truque`)
    REFERENCES `RPG`.`truque` (`id_truque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_truque_personagem_personagem1`
    FOREIGN KEY (`personagem_id_personagem`)
    REFERENCES `RPG`.`personagem` (`id_personagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_truque_personagem_truque1_idx` ON `RPG`.`truque_personagem` (`truque_id_truque` ASC) VISIBLE;

CREATE INDEX `fk_truque_personagem_personagem1_idx` ON `RPG`.`truque_personagem` (`personagem_id_personagem` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `RPG`.`caracteristicas_personagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RPG`.`caracteristicas_personagem` ;

CREATE TABLE IF NOT EXISTS `RPG`.`caracteristicas_personagem` (
  `id_caracteristicas_personagem` INT NOT NULL AUTO_INCREMENT,
  `id_personagem` INT NOT NULL,
  `idade` INT NULL,
  `cor_olhos` VARCHAR(45) NULL,
  `cor_pele` VARCHAR(45) NULL,
  `cor_cabelo` VARCHAR(45) NULL,
  `peso` FLOAT NULL,
  `altura` FLOAT NULL,
  `imagem_personagem` VARCHAR(300) NULL,
  PRIMARY KEY (`id_caracteristicas_personagem`),
  CONSTRAINT `fk_caracteristicas_personagem_personagem1`
    FOREIGN KEY (`id_personagem`)
    REFERENCES `RPG`.`personagem` (`id_personagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_caracteristicas_personagem_personagem1_idx` ON `RPG`.`caracteristicas_personagem` (`id_personagem` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `RPG`.`armas_personagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RPG`.`armas_personagem` ;

CREATE TABLE IF NOT EXISTS `RPG`.`armas_personagem` (
  `id_armas_personagem` INT NOT NULL,
  `id_personagem` INT NOT NULL,
  `id_tipo_dano` INT NOT NULL,
  `nome_arma` VARCHAR(45) NULL,
  `dado_dano` VARCHAR(12) NULL,
  `bonus` FLOAT NULL,
  `extra` VARCHAR(120) NULL,
  PRIMARY KEY (`id_armas_personagem`),
  CONSTRAINT `fk_armas_personagem_personagem1`
    FOREIGN KEY (`id_personagem`)
    REFERENCES `RPG`.`personagem` (`id_personagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_armas_personagem_tipo_dano1`
    FOREIGN KEY (`id_tipo_dano`)
    REFERENCES `RPG`.`tipo_dano` (`id_tipo_dano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_armas_personagem_personagem1_idx` ON `RPG`.`armas_personagem` (`id_personagem` ASC) VISIBLE;

CREATE INDEX `fk_armas_personagem_tipo_dano1_idx` ON `RPG`.`armas_personagem` (`id_tipo_dano` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `RPG`.`dinheiro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RPG`.`dinheiro` ;

CREATE TABLE IF NOT EXISTS `RPG`.`dinheiro` (
  `id_dinheiro` INT NOT NULL,
  `id_personagem` INT NOT NULL,
  `prata` FLOAT NULL,
  `ouro` FLOAT NULL,
  `cobre` FLOAT NULL,
  `platina` FLOAT NULL,
  `diamante` FLOAT NULL,
  PRIMARY KEY (`id_dinheiro`),
  CONSTRAINT `fk_dinheiro_personagem1`
    FOREIGN KEY (`id_personagem`)
    REFERENCES `RPG`.`personagem` (`id_personagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_dinheiro_personagem1_idx` ON `RPG`.`dinheiro` (`id_personagem` ASC) VISIBLE;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
