from .personagem_atributos import Personagem_Atributos
from .personagem_habilidades import Personagem_Habilidades
from .personagem_status_base import Personagem_Status_Base
from .personagem_salvaguardas import Personagem_Salvaguardas
from .personagem_pericias import Personagem_Pericias
from .personagem_caracteristicas import Personagem_Caracteristicas
from .personagem import Personagem
