from .test_user import UserTest
from .test_saving_throw import SavingThrowTest
from .test_room import RoomTest
from .test_race import RaceTest
from .test_character import CharacterTest
from .test_character_status_base import CharacterStatusBaseTest
from .test_character_saving_throw import CharacterSavingThrowTest
from .test_character_skill import CharacterSkillTest
from .test_character_spell import CharacterSpellTest
from .test_character_equipment import CharacterEquipmentTest
from .test_character_characteristics import CharacterCharacteristicsTest
from .test_character_attribute import CharacterAttributeTest
from .test_skill import SkillTest
from .test_message import MessageTest
from .test_spell import SpellTest
from .test_flask_character import TestNewCharacterView
from .test_flask_login import TestLoginView
from .test_flask_user_register import TestNewUserView
from .test_equipment import EquipmentTest
from .test_classe import ClasseTest