from .test_usuario import UsuarioTest
from .test_salvaguarda import SalvaguardaTest
from .test_room import TestRoom
from .test_raca import RacaTest
from .test_personagem import PersonagemTest
from .test_personagem_status_base import PersonagemStatusBaseTest
from .test_personagem_salvaguardas import PersonagemSalvaguardaTest
from .test_personagem_pericias import PersonagemPericiasTest
from .test_personagem_habilidades import PersonagemHabilidadesTest
from .test_personagem_atributos import PersonagemAtributosTest
from .test_pericia import PericiaTest
from .test_message import TestMessage
from .test_habilidade import HabilidadeTest
from .test_flask_personagem import TestNewPersonagemView
from .test_flask_login import TestLoginView
from .test_flask_cadastro_usuario import TestNewUserView
from .test_classe import ClasseTest